var VERSION='1.0.0'
var FULL_VERSION='1.0.0'
var AUTHORS='Nemo157 (Wim Looman) <wim@nemo157.com>'

use-standard-lifecycle
webpack-goals
tsd-goals
k-standard-goals
dnu-goals webProject='src/DocNuget/project.json'
